# Generated by Django 4.0.1 on 2023-03-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('middlename', models.CharField(max_length=50, verbose_name='Отчество')),
                ('birthday', models.DateField(verbose_name='День рождения')),
                ('stud_id', models.IntegerField(max_length=12, verbose_name='ИИН')),
                ('diploma_title', models.CharField(max_length=100, verbose_name='Тема дипломного проекта')),
            ],
            options={
                'verbose_name': 'Студенты',
            },
        ),
    ]
