# Generated by Django 3.0.7 on 2023-03-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('middlename', models.CharField(max_length=50, verbose_name='Отчество')),
                ('birthday', models.DateField(verbose_name='День рождения')),
                ('diploma_title', models.CharField(max_length=100, verbose_name='Тема дипломного проекта')),
            ],
            options={
                'verbose_name': 'Student',
            },
        ),
    ]
