# Generated by Django 4.0.2 on 2023-03-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('middlename', models.CharField(max_length=50, verbose_name='Отчество')),
                ('birthday', models.DateField(verbose_name='День рождения')),
                ('diploma_title', models.CharField(max_length=100, verbose_name='Тема дипломного проекта')),
                ('iin', models.CharField(default=' ', max_length=100, verbose_name='ИИН')),
                ('name_eng', models.CharField(default=' ', max_length=100, verbose_name='Имя на английском')),
                ('lastname_eng', models.CharField(default=' ', max_length=100, verbose_name='Фамилия на английском')),
                ('middlename_eng', models.CharField(default=' ', max_length=100, verbose_name='Отчество на английском')),
                ('id_card', models.CharField(default=' ', max_length=100, verbose_name='№ удостоверения личности/паспорта')),
                ('speciality', models.CharField(default=' ', max_length=100, verbose_name='Специальность')),
                ('prez_diploma', models.FileField(upload_to='uploads/', verbose_name='Презентация')),
                ('recen_diploma', models.FileField(upload_to='uploads/', verbose_name='Рецензия')),
                ('feedback_diploma', models.FileField(upload_to='uploads/', verbose_name='Отзыв руководителя')),
                ('antiplagiat', models.FileField(upload_to='uploads/', verbose_name='Антиплагиат')),
            ],
            options={
                'verbose_name': 'Student',
            },
        ),
    ]
