# Generated by Django 3.0.7 on 2023-03-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='lastname',
            new_name='lastname_kz',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='middlename',
            new_name='middlename_kz',
        ),
        migrations.AlterField(
            model_name='students',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
