# Generated by Django 3.0.7 on 2023-03-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='iin',
            field=models.CharField(default='default_value', max_length=12, verbose_name='ИИН'),
        ),
    ]
