# Generated by Django 3.0.7 on 2023-03-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_students_iin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='iin',
            field=models.CharField(default='default_value', max_length=1000, verbose_name='ИИН'),
        ),
    ]
