# Generated by Django 3.0.7 on 2023-03-29 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_auto_20230329_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='id_card',
            field=models.CharField(default=' ', max_length=100, verbose_name='№ удостоверения личности/паспорта'),
        ),
        migrations.AddField(
            model_name='students',
            name='iin',
            field=models.CharField(default='default_value', max_length=100, verbose_name='ИИН'),
        ),
        migrations.AddField(
            model_name='students',
            name='speciality',
            field=models.CharField(default=' ', max_length=100, verbose_name='Специальность'),
        ),
    ]
